### ISSUE TITLE
problem with installation

### ISSUE THREAD

**Issue by toxema** [aktos-io/scadajs-template#4]
when i follow the instruction i got following error
--------------------------------------------------------------------------
yakut@yakut-ubuntu:~/scadajs-test/myproject$ sudo ./scada.js/install-modules.sh

Using /home/yakut/scadajs-test/myproject/scada.js.conf file...
-----------------------------------
./
./lib/dcs
./lib/dcs/transports/tcp/
./lib/dcs/services/dcs-proxy/socket-io/
./lib/dcs/services/couch-dcs/

Installing Modules
-----------------------------------
 *** Installing dependencies for: "./"

(removing package-lock.json)

> utf-8-validate@3.0.4 install /home/yakut/scadajs-test/myproject/scada.js/node_modules/utf-8-validate
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.3.0
prebuild-install info looking for local prebuild @ prebuilds/utf-8-validate-v3.0.4-node-v67-linux-x64.tar.gz
prebuild-install info looking for cached prebuild @ /home/yakut/.npm/_prebuilds/https-github.com-websockets-utf-8-validate-releases-download-v3.0.4-utf-8-validate-v3.0.4-node-v67-linux-x64.tar.gz
prebuild-install http request GET https://github.com/websockets/utf-8-validate/releases/download/v3.0.4/utf-8-validate-v3.0.4-node-v67-linux-x64.tar.gz
prebuild-install http 404 https://github.com/websockets/utf-8-validate/releases/download/v3.0.4/utf-8-validate-v3.0.4-node-v67-linux-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=11.6.0 runtime=node arch=x64 platform=linux)
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/yakut/scadajs-test/myproject/scada.js/node_modules/utf-8-validate/build'
gyp ERR! System Linux 4.15.0-50-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/yakut/scadajs-test/myproject/scada.js/node_modules/utf-8-validate
gyp ERR! node -v v11.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN marked-terminal@3.2.0 requires a peer of marked@^0.4.0 || ^0.5.0 || ^0.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN scada@0.4.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! utf-8-validate@3.0.4 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the utf-8-validate@3.0.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/yakut/.npm/_logs/2019-05-24T19_30_02_548Z-debug.log
 *** Installing dependencies for: "./lib/dcs"

(removing package-lock.json)
audited 111 packages in 1.153s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
 *** Installing dependencies for: "./lib/dcs/transports/tcp/"

(removing package-lock.json)
npm WARN tcp@0.0.1 No repository field.

audited 27 packages in 1.057s
found 0 vulnerabilities

 *** Installing dependencies for: "./lib/dcs/services/dcs-proxy/socket-io/"

(removing package-lock.json)
npm WARN socketio@1.0.0 No description
npm WARN socketio@1.0.0 No repository field.

audited 89 packages in 1.233s
found 0 vulnerabilities

 *** Installing dependencies for: "./lib/dcs/services/couch-dcs/"

(removing package-lock.json)
npm WARN couch-dcs@1.0.0 No repository field.

audited 202 packages in 1.357s
found 0 vulnerabilities
![Screenshot from 2019-05-24 22-32-35](https://user-images.githubusercontent.com/3610757/58352986-e6cd5300-7e75-11e9-9896-75243155e9c9.png)
[2019-05-24T19_30_46_094Z-debug.log](https://github.com/aktos-io/scadajs-template/files/3218381/2019-05-24T19_30_46_094Z-debug.log)

**Comment by toxema** [comment]
i found the problem:
_prebuild-install http 404 https://github.com/websockets/utf-8-validate/releases/download/v3.0.4/utf-8-validate-v3.0.4-node-v67-linux-x64.tar.gz_

utf-8-validate  version 3.0.4 not exist anymore. change utf-8-validate  version to 5.0.2 in package.json file.

**Comment by ceremcem** [comment]
I can not reproduce the problem because v3.0.4 is available *for me*. Apparently the precompiled binaries are compiled per NodeJS version and your NodeJS version (`node-v67`) is not available [among the assets](https://github.com/websockets/utf-8-validate/releases/tag/v3.0.4). What is your `node --version`?

I completely removed the `utf-8-validate` package since it's not directly used by ScadaJS. Please update the project with:
```
./pull.sh
```
and see if it's fixed.

FYI: You shouldn't use "`sudo`" for `./scada.js/install-modules.sh`. `sudo` is only needed for the commands that are explicitly marked with "run with admin/root privileges" statement.

**Comment by toxema** [comment]
everything works fine right now. Thank you.
